name: TestRunner Template
on: 
  push:
    branches:
      - master

env: 
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testRunnerInAllModes:
    name: Test in ${{ matrix.testMode }} ✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - EditMode
          - PlayMode
    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Restore Library cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-OwlAndJackalope.UX
          restore-keys: |
            Library-
            
      # Configure test runner
      - uses: game-ci/unity-test-runner@v2
        id: testRunner
        with:
          testMode: ${{ matrix.testMode }}
          checkName: ${{ matrix.testMode }} test results
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 2021.3.11f1

      # Upload artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: Test results (${{ matrix.testMode }})
          path: ${{ steps.testRunner.outputs.artifactsPath }}
